config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:show, :index, :new, :create] do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  validates :content, presence: true
  validates  :rating, presence: true, numericality: { only_integer: true }, inclusion: { in: [0, 1, 2, 3, 4, 5] }
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = @restaurant.reviews
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save(restaurant_params)
      redirect_to restaurants_path
    else
      render :new
    end
  end

private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurants_path(@restaurant)
  end


private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <h1>RESTAURANTS REVIEWS DOT COM .... <del>previously Yelp</del></h1>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h2>All Restaurants</h2>

<ul>
  <% @restaurants.each do |restaurant| %>
    <ul>
      <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
    </ul>
  <% end %>
</ul>
<p><%= link_to "Create New Restaurant", new_restaurant_path %></p>

app/views/restaurants/new.html.erb
<h1>Add a new Restaurant</h1>

<%= simple_form_for(@restaurant) do |f| %>
 <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
  <% if @restaurant.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @restaurant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%=  @restaurant.name %></h1>
  <ul><%= "Style: #{@restaurant.category}"%></ul>
  <ul><%= "Location: #{@restaurant.address}" %></ul>

  <div>
    <h2>Whats the word on the street?</h2>
    <% @reviews.each do |review| %>
      <ul> <%= review.content %>
           <%=" // #{review.rating} stars" %>
      </ul>
    <%end%>

  </div>
<p><%= link_to "add a review", new_restaurant_review_path(@restaurant)%></p>


<p><%= link_to "back to all restaurants",restaurants_path %></p>

app/views/reviews/new.html.erb
<h1>Add a review </h1>

<%= simple_form_for([@restaurant, @review]) do |f| %>
 <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Add Review", class: "btn btn-primary" %>
<% end %>